---
spring:
  cloud:
    gcp:
      firestore:
        project-id: ${PROJECT_ID}
        credentials:
          location: classpath:service_account_stg.json

extension:
  api:
    rss:
      base-url: https://www.fukuishimbun.co.jp/list/feed/rss
      connect-timeout: 10000
      read-timeout: 10000
      max-in-memory-size: 16777216