---
spring:
  cloud:
    gcp:
      firestore:
        project-id: ${PROJECT_ID}

extension:
  api:
    rss:
      base-url: https://www.pref.fukui.lg.jp/news.xml
      connect-timeout: 10000
      read-timeout: 10000
      max-in-memory-size: 16777216