spring:
  application:
    name: cio-feeder
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  web:
    locale: ja_JP
  profiles:
    include: prod
    group:
      local:
        - local
        - rss
      prod:
        - prod
        - rss
